import { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Image from 'next/image'
import rougaroo from '../public/images/rougaroo.png'
import jdubsrub from '../public/images/jdubsrub.png'

import { initiateCheckout } from '../lib/payments.js'

import products from '../products.json'

const defaultCart = {
  products: {}
}

export default function Home() {

  const [cart, updateCart] = useState(defaultCart);

  const cartItems = Object.keys(cart.products).map(key => {
    const product = products.find(({ id }) => `${id}` === `${key}`);
    return {
      ...cart.products[key],
      pricePerItem: product.price
    }
  })

  console.log('cartItems', cartItems)


  const subtotal = cartItems.reduce((accumulator, { pricePerItem, quantity }) => {
    return accumulator + (pricePerItem * quantity)
  }, 0)

  console.log('subtotal', subtotal)


  function addToCart({ id } = {}) {
    updateCart(prev => {
      let cartState = { ...prev };
      // console.log('cartState before', cartState)

      if (cartState.products[id]) {
        cartState.products[id].quantity += 1;
      } else {
        cartState.products[id] = {
          id,
          quantity: 1
        }
      }
      // console.log('cartState after', cartState)
      return cartState;
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to J Dub&apos;s Rubs!
        </h1>

        <p className={styles.description}>
          The best barbecue rubs on earth
        </p>

        <p className={styles.description}>
          <strong>Items:</strong> 2
          <br />
          <strong>Total cost:</strong> $20
          <br />
          <button className={styles.button}>Check Out</button>
        </p>

        <ul className={styles.grid}>
          {products.map(product => {
            const { id, title, description, image, price } = product;
            return (
              <li key={id} className={styles.card}>
                <a href="#">
                  <Image
                    src={image}
                    alt={title}
                    width="500px"
                    height="500px"
                  />
                  <h2>{title}</h2>
                  <p>${price}</p>
                  <p>{description}</p>
                </a>
                <p>
                  <button className={styles.button} onClick={() => {
                    addToCart({ id });
                    // initiateCheckout({
                    //   lineItems: [
                    //     {
                    //       price: id,
                    //       quantity: 1
                    //     }
                    //   ]
                    // });
                  }}>Add to Cart</button>
                </p>
              </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}
